name: Makefile for git actions

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

      - name: Install dependencies
        run: make install-dependencies

      - name: Install tools
        run: make install-tools

      - name: Install
        run: make install

      - name: Run go errcheck
        run: make ci-errcheck

      - name: Run go fmt
        run: make ci-gofmt

      - name: Run go vet
        run: make ci-govet

      - name: Run lint
        run: make ci-lint

      - name: Run test
        run: make test-verbose-with-coverage

      - name: Run gover
        run: gover
